info:
  app:
    name: ${spring.application.name}
    version: 0.0.1
    description: Proxy Test Service.

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"

server:
  port: ${SERVER_PORT:8090}
