info:
  tags:
    environment: test

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8090}

spring:
  jmx:
    enabled: true
